# Generated by Django 2.2.3 on 2020-08-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_DeviceType',
            },
        ),
        migrations.CreateModel(
            name='ElectricMachinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voltage_level', models.IntegerField()),
                ('Polar_logarithm', models.IntegerField()),
                ('Power', models.FloatField()),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_ElectricMachinery',
            },
        ),
        migrations.CreateModel(
            name='Equipment_Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=20)),
                ('Main_Equipment_ID', models.CharField(max_length=20)),
                ('Fault_Equipment_Type', models.CharField(max_length=20)),
                ('Fault_Type', models.CharField(max_length=20)),
                ('Sub_Fault_Type', models.CharField(max_length=20)),
                ('Descriptions', models.CharField(max_length=100)),
                ('Fixed', models.BooleanField(default=False)),
                ('Line', models.CharField(max_length=20)),
                ('Caused_New_Feed_Offline', models.BooleanField(default=True)),
                ('From', models.DateTimeField()),
                ('To', models.DateTimeField()),
                ('Down_time', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ips_Equipment_Downtime',
            },
        ),
        migrations.CreateModel(
            name='InstallationPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Installation_position', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=6)),
                ('Describe', models.TextField()),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_InstallationPosition',
            },
        ),
        migrations.CreateModel(
            name='LogContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_user', models.CharField(max_length=20)),
                ('op', models.CharField(max_length=64)),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_LogContext',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=6)),
                ('Cycle', models.IntegerField()),
                ('Describe', models.TextField()),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_MaintenanceLevel',
            },
        ),
        migrations.CreateModel(
            name='OverhaulContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_type', models.CharField(max_length=20)),
                ('Overhaul_contents_description', models.TextField()),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_OverhaulContents',
            },
        ),
        migrations.CreateModel(
            name='OverhaulType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=6)),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_OverhaulType',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('Maintenance_strategy_code', models.CharField(max_length=20)),
                ('Installation_position', models.CharField(max_length=50)),
                ('Voltage_level', models.IntegerField()),
                ('Device_type', models.CharField(max_length=10)),
                ('Maintenance_level', models.IntegerField()),
                ('Describe', models.TextField()),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_Overview',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=32)),
                ('Login_name', models.CharField(max_length=20)),
                ('User_name', models.CharField(max_length=20)),
                ('Pwd', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=32)),
                ('Describe', models.TextField()),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_User',
            },
        ),
        migrations.CreateModel(
            name='VoltageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=6)),
                ('Add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ips_VoltageLevel',
            },
        ),
    ]
