# Generated by Django 2.2.3 on 2020-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_downtime',
            name='Descriptions',
            field=models.CharField(max_length=256),
        ),
    ]
