# Generated by Django 2.2.3 on 2020-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200807_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_downtime',
            name='Sub_Fault_Type',
            field=models.CharField(max_length=64),
        ),
    ]
