# Generated by Django 2.2.3 on 2020-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200807_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_downtime',
            name='Caused_New_Feed_Offline',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment_downtime',
            name='Fixed',
            field=models.CharField(max_length=20),
        ),
    ]
