# Generated by Django 2.2.3 on 2020-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200807_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_downtime',
            name='Descriptions',
            field=models.CharField(max_length=512),
        ),
    ]
