# Generated by Django 2.2.3 on 2020-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200807_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_downtime',
            name='Descriptions',
            field=models.CharField(max_length=2048),
        ),
    ]
